### ISSUE TITLE
Use of Lego

### ISSUE THREAD

**Issue by mike2nl** [Settorezero/Coviclock#1]
Hi @Cyb3rn0id,
finally someone who is crazy in the same way as me who builds esp stuff in Lego. I have a lot of Lego used for my esp8266 and esp32 projects. Fast and flexible where i need it. My kids are happy with the bed light switches and the panik buttons in the house. SO as meteo data with display and much more usefull things for me.

**Comment by Cyb3rn0id** [comment]
Thank you. In this [Google Photos Gallery](https://photos.app.goo.gl/a9PWPLTzMMWV21LJ8) is showed how I've built the enclosure using the bricks.
